# Generated by Django 4.1.2 on 2022-10-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='team_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва команди'),
        ),
    ]
